name = "zlib"
description = "Pure Ada zlib, gzip, raw Deflate, and native 7z compression"
version = "0.1.0"

authors = ["Bent Bracke"]
maintainers = ["Bent Bracke <bent@bracke.dk>"]
maintainers-logins = ["bracke"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["zlib", "deflate", "gzip", "compression", "ada"]

[[depends-on]]
gnat_native = "^15"

[[depends-on]]
cryptolib = "*"

[[actions]]
type = "test"
command = ["sh", "-c", "cd tests && alr build && ./bin/tests"]
