name = "zlib"
description = "Pure Ada zlib, gzip, and raw Deflate compression and decompression"
version = "0.1.0-dev"

authors = ["Bent Bracke"]
maintainers = ["Bent Bracke <bent@bracke.dk>"]
maintainers-logins = ["bracke"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["zlib", "deflate", "gzip", "compression", "ada"]

[[actions]]
type = "test"
command = ["sh", "-c", "cd tests && alr build && ./bin/tests"]
