with Zlib_Public_Tests;
with Zlib_Public_Checksum_Tests;
with Zlib_CRC32_Tests;
with Zlib_Bits_Tests;
with Zlib_Bit_Writer_Tests;
with Zlib_LZ77_Matcher_Tests;
with Zlib_Lazy_Matcher_Tests;
with Zlib_Lazy_Compression_Tests;
with Zlib_Block_Chooser_Tests;
with Zlib_Wrapper_Tests;
with Zlib_Huffman_Tests;
with Zlib_Inflate_Fixed_Tests;
with Zlib_Inflate_Dynamic_Tests;
with Zlib_Deflate_Stored_Tests;
with Zlib_Deflate_Fixed_Tests;
with Zlib_Deflate_Dynamic_Tests;
with Zlib_Deflate_Auto_Tests;
with Zlib_Auto_Block_Selection_Tests;
with Zlib_Compression_Level_Tests;
with Zlib_GZip_Output_Tests;
with Zlib_GZip_Metadata_Tests;
with Zlib_GZip_Broader_Compat_Tests;
with Zlib_GZip_Multimember_Tests;
with Zlib_Streaming_GZip_Metadata_Tests;
with Zlib_Huffman_Builder_Tests;
with Zlib_File_Tests;
with Zlib_Streaming_File_Tests;
with Zlib_Malformed_Tests;
with Zlib_Git_Fixture_Tests;
with Zlib_Streaming_Api_Tests;
with Zlib_Streaming_Compression_Api_Tests;
with Zlib_Raw_Compression_Api_Tests;
with Zlib_Deflate_Raw_Bridge_Tests;
with Zlib_Deflate_Raw_Stored_Tests;
with Zlib_Deflate_Raw_Fixed_Tests;
with Zlib_Deflate_Raw_Dynamic_Tests;
with Zlib_Deflate_Raw_Auto_Tests;
with Zlib_Streaming_Compress_Raw_Stored_Tests;
with Zlib_Streaming_Compress_Raw_Fixed_Tests;
with Zlib_Streaming_Compress_Raw_Dynamic_Tests;
with Zlib_Streaming_Compress_Raw_Auto_Tests;
with Zlib_Streaming_Compress_Stored_Tests;
with Zlib_Streaming_Compress_Fixed_Tests;
with Zlib_Streaming_Compress_Dynamic_Tests;
with Zlib_Streaming_Compress_Auto_Tests;
with Zlib_Streaming_Compress_Level_Tests;
with Zlib_Streaming_Compress_Conformance_Tests;
with Zlib_Streaming_Compress_GZip_Tests;
with Zlib_Streaming_Compress_Lifecycle_Tests;
with Zlib_Streaming_Compress_Finish_Tests;
with Zlib_Streaming_Compress_Bounds_Tests;
with Zlib_Streaming_Compress_Flush_Tests;
with Zlib_Stream_Bits_Tests;
with Zlib_Sliding_Window_Tests;
with Zlib_Streaming_Inflate_Stored_Tests;
with Zlib_Streaming_Inflate_Fixed_Tests;
with Zlib_Streaming_Inflate_Dynamic_Tests;
with Zlib_Streaming_GZip_Tests;
with Zlib_Streaming_Raw_Deflate_Tests;
with Zlib_Streaming_Lifecycle_Tests;
with Zlib_Streaming_Finish_Tests;
with Zlib_One_Shot_Streaming_Bridge_Tests;
with Zlib_Inflate_With_Header_Tests;
with Zlib_Inflate_Raw_Api_Tests;
with Zlib_Release_Contract_Tests;
with Zlib_Interop_Fixture_Tests;
with Zlib_Streaming_Equivalence_Tests;
with Zlib_Performance_Regression_Tests;
with Zlib_Wrapper_Mode_Conformance_Tests;
with Zlib_Cross_Api_Equivalence_Tests;
with Zlib_Malformed_Conformance_Tests;
with Zlib_Compression_Conformance_Tests;
with Zlib_Consumer_Fixture_Tests;
with Zlib_Streaming_Compression_Release_Tests;
with Zlib_Raw_Cross_Wrapper_Conformance_Tests;
with Zlib_Raw_Release_Tests;
with Zlib_Dictionary_Tests;
with Zlib_Streaming_Dictionary_Tests;
with Zlib_Fuzz_Smoke_Tests;
with Zlib_Seven_Zip_Tests;
with Zlib_Seven_Zip_Filter_Tests;
with Zlib_Seven_Zip_LZMA_Interop_Tests;
with Zlib_ZIP_External_Codec_Tests;

package body Zlib_Suite is
   pragma Warnings (Off, "use of an anonymous access type allocator");

   function Suite return AUnit.Test_Suites.Access_Test_Suite is
      Result : constant AUnit.Test_Suites.Access_Test_Suite :=
        new AUnit.Test_Suites.Test_Suite;
   begin
      --  Public API and checksum primitives.
      Result.Add_Test (new Zlib_Public_Tests.Test_Case);
      Result.Add_Test (new Zlib_Public_Checksum_Tests.Test_Case);
      Result.Add_Test (new Zlib_CRC32_Tests.Test_Case);

      --  Bit readers/writers, wrapper parsing, Huffman, and sliding window.
      Result.Add_Test (new Zlib_Bits_Tests.Test_Case);
      Result.Add_Test (new Zlib_Bit_Writer_Tests.Test_Case);
      Result.Add_Test (new Zlib_LZ77_Matcher_Tests.Test_Case);
      Result.Add_Test (new Zlib_Lazy_Matcher_Tests.Test_Case);
      Result.Add_Test (new Zlib_Lazy_Compression_Tests.Test_Case);
      Result.Add_Test (new Zlib_Block_Chooser_Tests.Test_Case);
      Result.Add_Test (new Zlib_Wrapper_Tests.Test_Case);
      Result.Add_Test (new Zlib_Huffman_Tests.Test_Case);
      Result.Add_Test (new Zlib_Huffman_Builder_Tests.Test_Case);
      Result.Add_Test (new Zlib_Stream_Bits_Tests.Test_Case);
      Result.Add_Test (new Zlib_Sliding_Window_Tests.Test_Case);

      --  One-shot inflate, compression, file helpers, and malformed inputs.
      Result.Add_Test (new Zlib_Inflate_Fixed_Tests.Test_Case);
      Result.Add_Test (new Zlib_Inflate_Dynamic_Tests.Test_Case);
      Result.Add_Test (new Zlib_Inflate_With_Header_Tests.Test_Case);
      Result.Add_Test (new Zlib_Inflate_Raw_Api_Tests.Test_Case);
      Result.Add_Test (new Zlib_Deflate_Stored_Tests.Test_Case);
      Result.Add_Test (new Zlib_Deflate_Fixed_Tests.Test_Case);
      Result.Add_Test (new Zlib_Deflate_Dynamic_Tests.Test_Case);
      Result.Add_Test (new Zlib_Deflate_Auto_Tests.Test_Case);
      Result.Add_Test (new Zlib_Auto_Block_Selection_Tests.Test_Case);
      Result.Add_Test (new Zlib_Compression_Level_Tests.Test_Case);
      Result.Add_Test (new Zlib_GZip_Output_Tests.Test_Case);
      Result.Add_Test (new Zlib_GZip_Metadata_Tests.Test_Case);
      Result.Add_Test (new Zlib_GZip_Broader_Compat_Tests.Test_Case);
      Result.Add_Test (new Zlib_GZip_Multimember_Tests.Test_Case);
      Result.Add_Test (new Zlib_File_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_File_Tests.Test_Case);
      Result.Add_Test (new Zlib_Malformed_Tests.Test_Case);

      --  Streaming inflate, wrapper modes, lifecycle, and equivalence.
      Result.Add_Test (new Zlib_Streaming_Api_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Compression_Api_Tests.Test_Case);
      Result.Add_Test (new Zlib_Raw_Compression_Api_Tests.Test_Case);
      Result.Add_Test (new Zlib_Deflate_Raw_Bridge_Tests.Test_Case);
      Result.Add_Test (new Zlib_Deflate_Raw_Stored_Tests.Test_Case);
      Result.Add_Test (new Zlib_Deflate_Raw_Fixed_Tests.Test_Case);
      Result.Add_Test (new Zlib_Deflate_Raw_Dynamic_Tests.Test_Case);
      Result.Add_Test (new Zlib_Deflate_Raw_Auto_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Compress_Raw_Stored_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Compress_Raw_Fixed_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Compress_Raw_Dynamic_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Compress_Raw_Auto_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Compress_Stored_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Compress_Fixed_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Compress_Dynamic_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Compress_Auto_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Compress_Level_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Compress_GZip_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_GZip_Metadata_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Compress_Lifecycle_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Compress_Finish_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Compress_Bounds_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Compress_Flush_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Compress_Conformance_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Inflate_Stored_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Inflate_Fixed_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Inflate_Dynamic_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_GZip_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Raw_Deflate_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Lifecycle_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Finish_Tests.Test_Case);
      Result.Add_Test (new Zlib_One_Shot_Streaming_Bridge_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Equivalence_Tests.Test_Case);
      Result.Add_Test (new Zlib_Performance_Regression_Tests.Test_Case);

      --  Interoperability, conformance fixtures, consumers, and release contract.
      Result.Add_Test (new Zlib_Git_Fixture_Tests.Test_Case);
      Result.Add_Test (new Zlib_Interop_Fixture_Tests.Test_Case);
      Result.Add_Test (new Zlib_Wrapper_Mode_Conformance_Tests.Test_Case);
      Result.Add_Test (new Zlib_Cross_Api_Equivalence_Tests.Test_Case);
      Result.Add_Test (new Zlib_Malformed_Conformance_Tests.Test_Case);
      Result.Add_Test (new Zlib_Compression_Conformance_Tests.Test_Case);
      Result.Add_Test (new Zlib_Consumer_Fixture_Tests.Test_Case);
      Result.Add_Test (new Zlib_Release_Contract_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Compression_Release_Tests.Test_Case);
      Result.Add_Test (new Zlib_Raw_Cross_Wrapper_Conformance_Tests.Test_Case);
      Result.Add_Test (new Zlib_Raw_Release_Tests.Test_Case);
      Result.Add_Test (new Zlib_Dictionary_Tests.Test_Case);
      Result.Add_Test (new Zlib_Streaming_Dictionary_Tests.Test_Case);
      Result.Add_Test (new Zlib_Fuzz_Smoke_Tests.Test_Case);
      Result.Add_Test (new Zlib_Seven_Zip_Tests.Test_Case);
      Result.Add_Test (new Zlib_Seven_Zip_Filter_Tests.Test_Case);
      Result.Add_Test (new Zlib_Seven_Zip_LZMA_Interop_Tests.Test_Case);
      Result.Add_Test (new Zlib_ZIP_External_Codec_Tests.Test_Case);
      return Result;
   end Suite;

   pragma Warnings (On, "use of an anonymous access type allocator");
end Zlib_Suite;
