with AUnit.Assertions; use AUnit.Assertions;
with Interfaces;
with Zlib;
with Zlib.Checksums;

package body Zlib_Dictionary_Tests is
   use type Interfaces.Unsigned_32;
   use type Zlib.Byte;
   use type Zlib.Status_Code;

   overriding function Name
     (T : Test_Case)
      return AUnit.Message_String
   is
      pragma Unreferenced (T);
   begin
      return AUnit.Format ("Zlib preset dictionary one-shot API");
   end Name;

   procedure Assert_Same
     (Actual   : Zlib.Byte_Array;
      Expected : Zlib.Byte_Array;
      Message  : String)
   is
   begin
      Assert (Actual'Length = Expected'Length, Message & ": length mismatch");
      for I in Expected'Range loop
         Assert
           (Actual (Actual'First + (I - Expected'First)) = Expected (I),
            Message & ": byte mismatch");
      end loop;
   end Assert_Same;

   function Dictionary return Zlib.Byte_Array is
   begin
      return [104, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100, 32,
              112, 114, 101, 102, 105, 120, 45, 115, 117, 102, 102, 105, 120];
   end Dictionary;

   function Payload return Zlib.Byte_Array is
   begin
      return [104, 101, 108, 108, 111];
   end Payload;

   procedure Test_Dictid_Is_Emitted
     (T : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T);
      Status : Zlib.Status_Code := Zlib.Ok;
      Dict   : constant Zlib.Byte_Array := Dictionary;
      Output : constant Zlib.Byte_Array :=
        Zlib.Deflate_With_Dictionary (Payload, Dict, Zlib.Stored, Status);
      ID     : constant Interfaces.Unsigned_32 := Zlib.Checksums.Adler32 (Dict);
   begin
      Assert (Status = Zlib.Ok, "dictionary deflate must succeed");
      Assert (Output'Length >= 6, "dictionary stream must include header and DICTID");
      Assert (Output (Output'First) = 16#78#, "CMF must be zlib Deflate CMF");
      Assert ((Natural (Output (Output'First + 1)) / 32) mod 2 = 1,
              "FLG must set FDICT");
      Assert
        (Interfaces.Unsigned_32 (Output (Output'First + 2)) =
           Interfaces.Shift_Right (ID, 24),
         "DICTID byte 0 must be big-endian Adler-32");
      Assert
        (Interfaces.Unsigned_32 (Output (Output'First + 3)) =
           (Interfaces.Shift_Right (ID, 16) and 16#FF#),
         "DICTID byte 1 must be big-endian Adler-32");
      Assert
        (Interfaces.Unsigned_32 (Output (Output'First + 4)) =
           (Interfaces.Shift_Right (ID, 8) and 16#FF#),
         "DICTID byte 2 must be big-endian Adler-32");
      Assert
        (Interfaces.Unsigned_32 (Output (Output'First + 5)) = (ID and 16#FF#),
         "DICTID byte 3 must be big-endian Adler-32");
   end Test_Dictid_Is_Emitted;

   procedure Test_Deflate_With_Dictionary_Roundtrip
     (T : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T);
      Status     : Zlib.Status_Code := Zlib.Ok;
      Dict       : constant Zlib.Byte_Array := Dictionary;
      Compressed : constant Zlib.Byte_Array :=
        Zlib.Deflate_With_Dictionary (Payload, Dict, Zlib.Auto, Status);
   begin
      Assert (Status = Zlib.Ok, "dictionary compression must succeed");
      declare
         Decoded : constant Zlib.Byte_Array :=
           Zlib.Inflate_With_Dictionary (Compressed, Dict, Status);
      begin
         Assert (Status = Zlib.Ok, "matching dictionary inflate must succeed");
         Assert_Same (Decoded, Payload, "dictionary one-shot roundtrip");
      end;
   end Test_Deflate_With_Dictionary_Roundtrip;

   procedure Test_Inflate_With_External_Dictionary_Stream
     (T : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T);
      --  Generated by zlib with zdict = Dictionary and payload = "hello".
      Compressed : constant Zlib.Byte_Array :=
        [16#78#, 16#F9#, 16#7D#, 16#F7#, 16#09#, 16#CD#,
         16#CB#, 16#00#, 16#49#, 16#00#, 16#00#, 16#06#, 16#2C#, 16#02#, 16#15#];
      Status : Zlib.Status_Code := Zlib.Ok;
      Output : constant Zlib.Byte_Array :=
        Zlib.Inflate_With_Dictionary (Compressed, Dictionary, Status);
   begin
      Assert (Status = Zlib.Ok, "external FDICT stream must inflate");
      Assert_Same (Output, Payload, "external FDICT payload");
   end Test_Inflate_With_External_Dictionary_Stream;

   procedure Test_Missing_Dictionary_Fails
     (T : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T);
      Compressed : constant Zlib.Byte_Array :=
        [16#78#, 16#F9#, 16#7D#, 16#F7#, 16#09#, 16#CD#,
         16#CB#, 16#00#, 16#49#, 16#00#, 16#00#, 16#06#, 16#2C#, 16#02#, 16#15#];
      Status : Zlib.Status_Code := Zlib.Ok;
      Output : constant Zlib.Byte_Array := Zlib.Inflate (Compressed, Status);
   begin
      pragma Unreferenced (Output);
      Assert
        (Status = Zlib.Unsupported_Preset_Dictionary,
         "FDICT without caller dictionary must fail deterministically");
   end Test_Missing_Dictionary_Fails;

   procedure Test_Wrong_Dictionary_Fails
     (T : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T);
      Compressed : constant Zlib.Byte_Array :=
        [16#78#, 16#F9#, 16#7D#, 16#F7#, 16#09#, 16#CD#,
         16#CB#, 16#00#, 16#49#, 16#00#, 16#00#, 16#06#, 16#2C#, 16#02#, 16#15#];
      Wrong  : constant Zlib.Byte_Array := [1 => 1, 2 => 2, 3 => 3];
      Status : Zlib.Status_Code := Zlib.Ok;
      Output : constant Zlib.Byte_Array :=
        Zlib.Inflate_With_Dictionary (Compressed, Wrong, Status);
   begin
      pragma Unreferenced (Output);
      Assert
        (Status = Zlib.Invalid_Checksum,
         "wrong dictionary DICTID must fail deterministically");
   end Test_Wrong_Dictionary_Fails;

   procedure Test_Large_Dictionary_Trailing_History
     (T : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T);
      Dict : Zlib.Byte_Array (1 .. 33_009);
      Compressed : constant Zlib.Byte_Array :=
        [16#78#, 16#F9#, 16#E2#, 16#E5#, 16#BF#, 16#44#,
         16#83#, 16#33#, 16#00#, 16#0C#, 16#72#, 16#02#, 16#7C#];
      Expected : constant Zlib.Byte_Array :=
        [84, 65, 73, 76, 45, 68, 73, 67, 84];
      Status : Zlib.Status_Code := Zlib.Ok;
   begin
      for I in 1 .. 33_000 loop
         Dict (I) := 65;
      end loop;
      Dict (33_001 .. 33_009) := Expected;

      declare
         Output : constant Zlib.Byte_Array :=
           Zlib.Inflate_With_Dictionary (Compressed, Dict, Status);
      begin
         Assert (Status = Zlib.Ok, "large dictionary stream must inflate");
         Assert_Same (Output, Expected, "only trailing dictionary history participates");
      end;
   end Test_Large_Dictionary_Trailing_History;

   overriding procedure Register_Tests
     (T : in out Test_Case)
   is
      use AUnit.Test_Cases.Registration;
   begin
      Register_Routine (T, Test_Dictid_Is_Emitted'Access, "dictionary DICTID is emitted");
      Register_Routine (T, Test_Deflate_With_Dictionary_Roundtrip'Access, "dictionary roundtrip");
      Register_Routine (T, Test_Inflate_With_External_Dictionary_Stream'Access, "inflate external FDICT stream");
      Register_Routine (T, Test_Missing_Dictionary_Fails'Access, "missing dictionary fails");
      Register_Routine (T, Test_Wrong_Dictionary_Fails'Access, "wrong dictionary fails");
      Register_Routine (T, Test_Large_Dictionary_Trailing_History'Access, "large dictionary trailing history");
   end Register_Tests;
end Zlib_Dictionary_Tests;
